# Generated by Django 3.0.8 on 2020-08-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetAQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('quote_is_processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='registered on')),
            ],
        ),
    ]
